server:
  port: 6006
spring:
  application:
    name: tx-distributed-patterns
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction_study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Q836184425
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 300000
      pool-name: transaction-insight-pool
      connection-test-query: SELECT 1
  kafka:
    bootstrap-servers: 192.168.254.2:9092,192.168.254.3:9092,192.168.254.4:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 2147483647
      compression-type: snappy
      batch-size: 32768
      buffer-memory: 67108864
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 5
