server:
  port: 6004
spring:
  application:
    name: tx-chaos-engineering
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  main:
    web-application-type: servlet
